/* ─────────────────────────────────────────────────────────────
   Rodizio · Menú completo — compartido entre mesero-app y
   panel-cliente. Script clasico, sin build, sin modulo.
   ───────────────────────────────────────────────────────────── */

      const MENU = [
        {
          cat: 'Entradas',
          items: [
            {
              id: 'ENT-01',
              img: '../icons/menu/en1.webp',
              nombre: 'Crema de Pollo ó Champiñones',
              desc: 'Suave crema elaborada en bechamel, a base de pechuga de pollo o champiñones.',
              precio: 24000,
            },
            {
              id: 'ENT-02',
              img: '../icons/menu/en2.webp',
              nombre: 'Sopa del Día',
              desc: 'Exquisita sopa especial de la casa a base de plátano, verduras y trocitos de carne seleccionadas.',
              precio: 20000,
            },
            {
              id: 'ENT-03',
              img: '../icons/menu/en3.webp',
              nombre: 'Coctel de Camarón',
              desc: '200 grs de camarones bañados en salsa golf o en salsa roja.',
              precio: 35000,
            },
            {
              id: 'ENT-04',
              img: '../icons/menu/en4.webp',
              nombre: 'Tuna a la Tártara',
              desc: 'Ensalada de la casa a base de atún, salsa tártara Rodizio, aguacate y tomate cherry, coronado con un crocante tostón.',
              precio: 25000,
            },
            {
              id: 'ENT-05',
              img: '../icons/menu/en5.webp',
              nombre: 'Ensalada al César',
              desc: 'Clásica mezcla de lechuga, crutones, tocineta y queso parmesano con aderezo césar.',
              precio: 20000,
            },
          ],
        },
        {
          cat: 'Para Compartir',
          items: [
            {
              id: 'COM-01',
              img: '../icons/menu/pc1.webp',
              nombre: 'Rodizio Casero',
              desc: '1000 gramos de proteína: punta de anca, chata, morrillo, chunchulla, lomito de cerdo, chorizo, morcilla y ubre, acompañado…',
              precio: 149900,
            },
            {
              id: 'COM-02',
              img: '../icons/menu/pc2.webp',
              nombre: 'Tostones de la Casa',
              desc: 'Crujientes y tostaditos platanitos acompañados de nuestra inigualable salsa tártara Rodizio.',
              precio: 10000,
            },
            {
              id: 'COM-03',
              img: '../icons/menu/pc3.webp',
              nombre: 'Porción de Morcillas',
              desc: 'Cuatro (4) inigualables y únicas morcillitas acompañadas de papa salada y yuca al vapor.',
              precio: 15000,
            },
            {
              id: 'COM-04',
              img: '../icons/menu/pc4.webp',
              nombre: 'Porción de Chorizo',
              desc: 'Dos chorizos importados al mejor estilo uruguayo acompañados de papa salada.',
              precio: 18000,
            },
            {
              id: 'COM-05',
              img: '../icons/menu/pc5.webp',
              nombre: 'Porción de Chicharrón',
              desc: '300 grs de chicharrón de cerdo acompañado de yuca al vapor y limoncito.',
              precio: 32000,
            },
            {
              id: 'COM-06',
              img: '../icons/menu/pc6.webp',
              nombre: 'Porción de Chunchulla ó Ubre',
              desc: '250 grs asadas a la parrilla acompañadas de papa salada o yuca al vapor. Recomendadísimo.',
              precio: 32000,
            },
            {
              id: 'COM-07',
              img: '../icons/menu/pc7.webp',
              nombre: 'Alitas Picantes',
              desc: '(12) Al mejor estilo americano, acompañadas de salsa miel-mostaza ó BBQ, ligeramente picantes.',
              precio: 32000,
            },
          ],
        },
        {
          cat: 'De la Parrilla',
          items: [
            {
              id: 'PAR-01',
              img: '../icons/menu/pa1.webp',
              nombre: 'Rodizio a la Mesa',
              desc: 'Buffet de 10 diferentes cortes de carnes entre res, pollo, cerdo y vísceras, servido a la mesa sin límite de consumo. Acompa…',
              precio: 99900,
            },
            {
              id: 'PAR-02',
              img: '../icons/menu/pa2.webp',
              nombre: 'Colita de Cuadril',
              desc: 'Corte selecto del chef, 400 grs de textura muy suave y mucho sabor, ubicado en la parte baja del sirloin.',
              precio: 80000,
            },
            {
              id: 'PAR-03',
              nombre: 'Plato Mixto',
              desc: 'Tradicional plato de la parrilla: churrasco, pollo, chinchulla, ubre y/o cerdo, con papa salada o a la francesa.',
              precio: 68000,
            },
            {
              id: 'PAR-04',
              img: '../icons/menu/pa4.webp',
              nombre: 'Baby Beef',
              desc: 'Tierno corte de lomo fino sin grasa, asado a la parrilla.',
              precio: 70000,
            },
            {
              id: 'PAR-05',
              img: '../icons/menu/pa5.webp',
              nombre: 'Punta de Anca',
              desc: 'Corte ubicado en el cuarto trasero de la res en su punto óptimo de maduración.',
              precio: 62000,
            },
            {
              id: 'PAR-06',
              img: '../icons/menu/pa6.webp',
              nombre: 'Picada Especial',
              desc: '(Para tres personas) Churrasco, pechuga, lomo de cerdo, morcilla, chorizo, tostones, arepitas, papas a la francesa y en…',
              precio: 119000,
            },
            {
              id: 'PAR-07',
              nombre: 'Bife Chorizo',
              desc: 'Corte argentino del centro de la chata de res a la parrilla. Término sugerido 1/2 ó 3/4.',
              precio: 58000,
            },
            {
              id: 'PAR-08',
              img: '../icons/menu/pa8.webp',
              nombre: 'Costillitas de Cerdo',
              desc: 'Seleccionadas costillas de cerdo a la parrilla, acompañadas de papas a la francesa. Elija entre BBQ y ahumada.',
              precio: 55000,
            },
            {
              id: 'PAR-09',
              img: '../icons/menu/pa9.webp',
              nombre: 'Churrasco',
              desc: 'Jugoso centro de chata de res en corte mariposa con punto óptimo de maduración y exquisito sabor.',
              precio: 52000,
            },
            {
              id: 'PAR-10',
              img: '../icons/menu/pa10.webp',
              nombre: 'Churrasco de Cerdo',
              desc: 'Jugoso centro de chata de cerdo en corte mariposa con punto óptimo de maduración y exquisito sabor.',
              precio: 46000,
            },
            {
              id: 'PAR-11',
              img: '../icons/menu/pa11.webp',
              nombre: 'Pollo al Rodizio',
              desc: 'Deliciosas presas de pollo asadas (4) a la brasa.',
              precio: 38000,
            },
          ],
        },
        {
          cat: 'Angus Beef',
          items: [
            {
              id: 'ANG-01',
              img: '../icons/menu/ab1.webp',
              nombre: 'New York Steak',
              desc: '350 grs de la más exquisita carne Angus Beef, tierna y ligeramente marmoleada, preparada a la brasa. Corte prove…',
              precio: 130000,
            },
            {
              id: 'ANG-02',
              img: '../icons/menu/ab2.webp',
              nombre: 'Asado de Tira',
              desc: 'Se caracteriza por ser uno de los cortes de mayor marmoleo. 350 grs de la mejor carne del mundo Certified Angus Beef…',
              precio: 120000,
            },
            {
              id: 'ANG-03',
              img: '../icons/menu/ab3.webp',
              nombre: 'Picanha',
              desc: 'Jugosa y tierna carne de novillo Certified Angus Beef servida en espada, cocinada a fuego lento, acompañada de feijoad…',
              precio: 315000,
            },
            {
              id: 'ANG-04',
              img: '../icons/menu/ab4.webp',
              nombre: 'Tomahawk Steak',
              desc: 'Corte fino de res Certified Angus Beef, una de las piezas más solicitadas en la mesa del mundo. Se trata de un corte…',
              precio: 132000,
            },
            {
              id: 'ANG-05',
              img: '../icons/menu/ab5.webp',
              nombre: 'Pincho Ipanema',
              desc: '280 grs de Picanha Certified Angus Beef acompañado de papas a la francesa, una arepita y una yuquita frita.',
              precio: 52000,
            },
            {
              id: 'ANG-06',
              img: '../icons/menu/ab6.webp',
              nombre: 'Sirloin Steak',
              desc: '200 grs de lomo ancho de res importado, Angus Beef Certified.',
              precio: 60000,
            },
            {
              id: 'ANG-07',
              img: '../icons/menu/ab7.webp',
              nombre: 'Espada Mundialista 2026',
              desc: '900 gramos de 3 cortes importados de 300 grs cada uno: sirloin, colita de cuadril y punta de anca de cerdo, acompañado…',
              precio: 269000,
            },
          ],
        },
        {
          cat: 'Burger Angus',
          items: [
            {
              id: 'BUR-01',
              img: '../icons/menu/ba1.webp',
              nombre: 'La Gardel',
              desc: '200 grs de carne Certified Angus Beef a la parrilla, chorizo argentino y corte mariposa, bañado en auténtico chimichurri…',
              precio: 46000,
            },
            {
              id: 'BUR-02',
              img: '../icons/menu/ba2.webp',
              nombre: 'La Mayamera',
              desc: '200 grs de carne Certified Angus Beef a la parrilla, 100 grs de queso asado, papitas fosforito, tocineta bañada en salsa BB…',
              precio: 46000,
            },
            {
              id: 'BUR-03',
              img: '../icons/menu/ba3.webp',
              nombre: 'Donald Trump',
              desc: '200 grs de carne Certified Angus Beef a la parrilla, aritos de cebolla, queso cheddar, tocineta bañada en salsa BBQ, vege…',
              precio: 44000,
            },
            {
              id: 'BUR-04',
              img: '../icons/menu/ba4.webp',
              nombre: 'De la Casa',
              desc: '200 grs de carne Certified Angus Beef a la parrilla, para los amantes de lo clásico: queso cheddar, tocineta, vegetales fre…',
              precio: 44000,
            },
          ],
        },
        {
          cat: 'De la Casa',
          items: [
            {
              id: 'CAS-01',
              nombre: 'Tri-mignon',
              desc: 'Combinación de (3) mignon de res, mignon de pollo y mignon de cerdo, bañados en tres diferentes salsas sobre una cama de puré de papa.',
              precio: 65000,
            },
            {
              id: 'CAS-02',
              img: '../icons/menu/dc2.webp',
              nombre: 'Filet Mignon',
              desc: 'Clásico de la casa, medallones de lomo de res envueltos en tocineta bañados en nuestra inigualable salsa demiglace…',
              precio: 66000,
            },
            {
              id: 'CAS-03',
              img: '../icons/menu/dc3.webp',
              nombre: 'Pollo a la Cremé',
              desc: 'Jugosa pechuga de pollo a la plancha bañada en salsa blanca con camarones ó champiñones.',
              precio: 53000,
            },
            {
              id: 'CAS-04',
              img: '../icons/menu/dc4.webp',
              nombre: 'Carne y Pasta',
              desc: 'Fetuccini o espagueti en salsa a elegir: 4 quesos, carbonara o napolitana. Elija entre churrasco, punta o baby beef.',
              precio: 53000,
            },
            {
              id: 'CAS-05',
              img: '../icons/menu/dc5.webp',
              nombre: 'Lomito al Strogonoff',
              desc: '(250 grs) Exquisito lomito fino cortado en tiras, bañado en salsa de vino y champiñones.',
              precio: 48000,
            },
            {
              id: 'CAS-06',
              img: '../icons/menu/dc6.webp',
              nombre: 'Milanesa Napolitana',
              desc: 'Lomo fino de res apanado con jamón, queso y bañado en salsa napolitana al gratín.',
              precio: 50000,
            },
            {
              id: 'CAS-07',
              img: '../icons/menu/dc7.webp',
              nombre: 'Pollo a la Diabla',
              desc: 'Deliciosa pechuga bañada en salsa rubia con un toque de pimienta y mostaza, acompañada de papas a la francesa.',
              precio: 49000,
            },
          ],
        },
        {
          cat: 'Del Mar',
          items: [
            {
              id: 'MAR-01',
              img: '../icons/menu/dm1.webp',
              nombre: 'Mixto de Mariscos',
              desc: 'Inigualable combinación de frutos del mar a la parrilla: mejillones, palmitos del mar, pota, calamar, pulpo, langostinos…',
              precio: 108000,
            },
            {
              id: 'MAR-02',
              img: '../icons/menu/dm2.webp',
              nombre: 'Langostinos',
              desc: '(6) Seleccionados langostinos directo del mar a la mesa. Elija entre Thermidor, al ajillo, al gratín o apanado de coco…',
              precio: 98000,
            },
            {
              id: 'MAR-03',
              img: '../icons/menu/dm3.webp',
              nombre: 'Salmón Marinera',
              desc: 'Filete de salmón a la plancha bañado en salsa de frutos del mar (calamar, pulpo, caracol, almeja y mejillón).',
              precio: 95000,
            },
            {
              id: 'MAR-04',
              img: '../icons/menu/dm4.webp',
              nombre: 'Róbalo Marinera',
              desc: 'Filete de róbalo a la plancha bañado en salsa de frutos del mar (calamar, pulpo, caracol, almeja y mejillón).',
              precio: 75000,
            },
            {
              id: 'MAR-05',
              img: '../icons/menu/dm5.webp',
              nombre: 'Salmón Fusión',
              desc: 'Filete de salmón a la parrilla bañado en salsa de lulo y soya, acompañado de arroz oriental.',
              precio: 75000,
            },
            {
              id: 'MAR-06',
              img: '../icons/menu/dm6.webp',
              nombre: 'Cazuela de Mariscos',
              desc: 'Plato típico de las costas colombianas al gratín con pulpo, calamar, almeja, caracol, camarón y langostinos.',
              precio: 71000,
            },
            {
              id: 'MAR-07',
              img: '../icons/menu/dm7.webp',
              nombre: 'Paella Española',
              desc: '(Para dos personas) Plato típico de la gastronomía española a base de arroz, vegetales, carnes y mariscos cocinados…',
              precio: 120000,
            },
            {
              id: 'MAR-08',
              img: '../icons/menu/dm8.webp',
              nombre: 'Salmón de la Casa',
              desc: 'Generosa porción de filete de salmón a la plancha acompañado de arroz negro en tinta de calamar.',
              precio: 75000,
            },
            {
              id: 'MAR-09',
              img: '../icons/menu/dm9.webp',
              nombre: 'Róbalo Buena Mujer',
              desc: 'Filete de róbalo en salsa de champiñones y camarones gratinado, servido en una cama de puré de papa.',
              precio: 71000,
            },
            {
              id: 'MAR-10',
              img: '../icons/menu/dm10.webp',
              nombre: 'Róbalo a la Cremé',
              desc: 'Filete de róbalo con camarón y/o champiñón bañado en una deliciosa salsa rubia al gratín.',
              precio: 71000,
            },
          ],
        },
        {
          cat: 'Menú Infantil',
          items: [
            {
              id: 'INF-01',
              img: '../icons/menu/mi1.webp',
              nombre: 'Mini - Hamburguesa',
              desc: 'Acompañado de papas a la francesa, un juguito y un juguete y sorpresa.',
              precio: 28000,
            },
            {
              id: 'INF-02',
              img: '../icons/menu/mi2.webp',
              nombre: 'Pechuguita Apanada',
              desc: 'Acompañado de papas a la francesa, un juguito y un juguete y sorpresa.',
              precio: 28000,
            },
            {
              id: 'INF-03',
              img: '../icons/menu/mi3.webp',
              nombre: 'Nuggets de Pollo',
              desc: 'Acompañado de papas a la francesa, un juguito y un juguete y sorpresa.',
              precio: 28000,
            },
            {
              id: 'INF-04',
              img: '../icons/menu/mi4.webp',
              nombre: 'Mini - Perro',
              desc: 'Acompañado de papas a la francesa, un juguito y un juguete y sorpresa.',
              precio: 28000,
            },
          ],
        },
        {
          cat: 'Postres',
          items: [
            {
              id: 'POS-01',
              img: '../icons/menu/po1.webp',
              nombre: 'Mousse de Maracuyá',
              desc: 'Típico de la gastronomía brasileña, súper refrescante.',
              precio: 15000,
            },
            {
              id: 'POS-02',
              img: '../icons/menu/po2.webp',
              nombre: 'Brownie con Helado',
              desc: 'Brownie de chocolate caliente cubierto de una bolita de helado de vainilla bañado en salsa de caramelo.',
              precio: 12000,
            },
            {
              id: 'POS-03',
              img: '../icons/menu/po3.webp',
              nombre: 'Quesillo',
              desc: 'Delicioso y suave quesillo de leche bañado en salsa de caramelo.',
              precio: 12000,
            },
            {
              id: 'POS-04',
              img: '../icons/menu/po4.webp',
              nombre: 'Brevas con Arequipe',
              desc: 'Típico postre bogotano que se prepara con brevas cocidas en azúcar o caramelo, cubiertas con arequipe.',
              precio: 12000,
            },
            {
              id: 'POS-05',
              nombre: 'Arequipe Flambeado',
              desc: 'Arequipe gratinado con queso mozzarella y parmesano, flambeado con coñac.',
              precio: 12000,
            },
            {
              id: 'POS-06',
              img: '../icons/menu/po6.webp',
              nombre: 'Copa de Helado',
              desc: 'Helado de vainilla bañado con salsa de chocolate.',
              precio: 15000,
            },
          ],
        },
        {
          cat: 'Bebidas',
          items: [
            { id: 'BEB-01', nombre: 'Limonada Cerezada', desc: '', precio: 15000, img: '../icons/menu/be1.webp' },
            { id: 'BEB-02', nombre: 'Limonada de Coco', desc: '', precio: 15000, img: '../icons/menu/be2.webp' },
            {
              id: 'BEB-03',
              img: '../icons/menu/be3.webp',
              nombre: 'Jugos Naturales',
              desc: 'Sabor de su preferencia.',
              precio: 11000,
            },
            {
              id: 'BEB-04',
              img: '../icons/menu/be4.webp',
              nombre: 'Frappes',
              desc: 'Sabor de su preferencia.',
              precio: 11000,
            },
            {
              id: 'BEB-05',
              img: '../icons/menu/be5.webp',
              nombre: 'Coca-Cola Pet 400 ml',
              desc: 'Mezcla de azúcar y aceites de naranja, limón y vainilla.',
              precio: 7000,
            },
            {
              id: 'BEB-06',
              img: '../icons/menu/be6.webp',
              nombre: 'Coca-Cola Zero Pet 400 ml',
              desc: 'Zero es una de las variantes no calóricas de Coca-Cola.',
              precio: 7000,
            },
            {
              id: 'BEB-07',
              img: '../icons/menu/be7.webp',
              nombre: 'Manzana Postobón 400 ml',
              desc: 'Bebida gaseosa ideal para refrescar y quitar la sed, aspecto líquido color rosado, refrescante.',
              precio: 6000,
            },
            {
              id: 'BEB-08',
              img: '../icons/menu/be8.webp',
              nombre: 'Uva Postobón 400 ml',
              desc: 'Con un dulce sabor a uva, refrescante, colorida y la favorita para los colombianos.',
              precio: 6000,
            },
            {
              id: 'BEB-09',
              img: '../icons/menu/be9.webp',
              nombre: '7up 400 ml',
              desc: 'A base de agua carbonatada con sabor a lima o limón, incolora y sin cafeína.',
              precio: 6000,
            },
            {
              id: 'BEB-10',
              img: '../icons/menu/be10.webp',
              nombre: 'Colombiana 400 ml',
              desc: 'Con un sabor espumoso de cola champán, perfecta para fiestas, reuniones y picnics.',
              precio: 6000,
            },
            {
              id: 'BEB-11',
              img: '../icons/menu/be11.webp',
              nombre: 'Hipinto 400 ml',
              desc: 'Bebida gaseosa que representa la cultura santandereana, sabores kola y piña.',
              precio: 6000,
            },
            {
              id: 'BEB-12',
              img: '../icons/menu/be12.webp',
              nombre: 'Agua Mineral Manantial',
              desc: 'Agua sin gas Manantial.',
              precio: 9000,
            },
            {
              id: 'BEB-13',
              img: '../icons/menu/be13.webp',
              nombre: 'Heineken 269 ml',
              desc: 'Ligero sabor dulce de la malta pilsen y su amargor suave, cerveza seca de cuerpo ligero.',
              precio: 10000,
            },
            {
              id: 'BEB-14',
              img: '../icons/menu/be14.webp',
              nombre: 'Club Colombia Dorada 330 ml',
              desc: 'Ideal si quieres sentir en tu paladar el sabor refrescante y balanceado entre malta y lúpulo.',
              precio: 10000,
            },
            {
              id: 'BEB-15',
              img: '../icons/menu/be15.webp',
              nombre: 'Club Colombia Roja 330 ml',
              desc: 'Notas ligeramente amargas que contrastan con los sabores dulces y caramelo.',
              precio: 10000,
            },
            {
              id: 'BEB-16',
              img: '../icons/menu/be16.webp',
              nombre: 'Águila Original 355 ml',
              desc: 'Refrescante, con un sabor suave y un porcentaje moderado de alcohol.',
              precio: 10000,
            },
            {
              id: 'BEB-17',
              img: '../icons/menu/be17.webp',
              nombre: 'Águila Light 330 ml',
              desc: 'Sabor suave con poco amargor.',
              precio: 10000,
            },
            {
              id: 'BEB-18',
              img: '../icons/menu/be18.webp',
              nombre: 'Póker 330 ml',
              desc: 'Sabor amargo con un toque de notas dulces.',
              precio: 10000,
            },
            {
              id: 'BEB-19',
              img: '../icons/menu/be19.webp',
              nombre: 'Coronita 210 ml',
              desc: 'Moderadamente dulce, recuerda el sabor del cereal. Amargor limpio y ligero.',
              precio: 12000,
            },
            {
              id: 'BEB-20',
              img: '../icons/menu/be20.webp',
              nombre: 'Corona 355 ml',
              desc: 'Moderadamente dulce, recuerda el sabor del cereal. Amargor limpio y ligero.',
              precio: 15000,
            },
            {
              id: 'BEB-21',
              img: '../icons/menu/be21.webp',
              nombre: 'Soda Hatsu Frambuesa & Rosas',
              desc: 'Soda rosa de sabor dulce y delicioso, mezcla frutal y herbal.',
              precio: 10000,
            },
            {
              id: 'BEB-22',
              img: '../icons/menu/be22.webp',
              nombre: 'Soda Hatsu Limón & Hierbabuena',
              desc: 'Soda amarilla de sabor especial y aroma relajante, mezcla frutal y herbal.',
              precio: 10000,
            },
            {
              id: 'BEB-23',
              img: '../icons/menu/be23.webp',
              nombre: 'Soda Hatsu Sandía & Albahaca',
              desc: 'Soda verde de sabor tropical y refrescante, mezcla frutal y herbal.',
              precio: 10000,
            },
            {
              id: 'BEB-24',
              img: '../icons/menu/be24.webp',
              nombre: 'Soda Hatsu Uva Blanca & Romero',
              desc: 'Soda ámbar de sabor especial y aroma relajante, mezcla frutal y herbal.',
              precio: 10000,
            },
            {
              id: 'BEB-25',
              img: '../icons/menu/be25.webp',
              nombre: 'Soda',
              desc: 'Perfecta para acompañar tus mejores momentos, bebida hecha de fusiones de sabores.',
              precio: 5000,
            },
            {
              id: 'BEB-26',
              img: '../icons/menu/be26.webp',
              nombre: 'Bebida Energizante RedBull x 250 ml',
              desc: '',
              precio: 10000,
            },
            {
              id: 'BEB-27',
              img: '../icons/menu/be27.webp',
              nombre: 'Canada Dry Ginger Ale',
              desc: 'Bebida refrescante, saborizada con sabor a jengibre, ideal para fusionar con otros sabores.',
              precio: 6000,
            },
            {
              id: 'BEB-28',
              img: '../icons/menu/be28.webp',
              nombre: 'Canada Dry Agua Tónica',
              desc: 'Bebida gasificada y refrescante, aromatizada con quinina.',
              precio: 6000,
            },
            {
              id: 'BEB-29',
              img: '../icons/menu/be29.webp',
              nombre: 'Té Hatsu Negro & Jugo de Limón',
              desc: 'Té revitalizante, saludable y refrescante, alto contenido de teína.',
              precio: 12000,
            },
            {
              id: 'BEB-30',
              img: '../icons/menu/be30.webp',
              nombre: 'Té Hatsu Blanco sabor Mangostino',
              desc: 'Té blanco de sabor muy suave, hecho con las hojas más jóvenes de la planta.',
              precio: 12000,
            },
            {
              id: 'BEB-31',
              img: '../icons/menu/be31.webp',
              nombre: 'Té Hatsu Carambolo & Flor de Loto',
              desc: 'Bebida de té 0 calorías y 0 carbohidratos, mezcla de carambolo y flor de loto.',
              precio: 12000,
            },
            {
              id: 'BEB-32',
              img: '../icons/menu/be32.webp',
              nombre: 'Té Hatsu sabor a Granada & Mora Azul',
              desc: 'Bebida de té 0 calorías y 0 carbohidratos, mezcla de té blanco con granada y mora azul.',
              precio: 12000,
            },
            {
              id: 'BEB-33',
              img: '../icons/menu/be33.webp',
              nombre: 'Té Hatsu Rojo sabor Frutos Rojos',
              desc: 'Té rojo, variedad exclusiva cultivada en China, gran significado histórico.',
              precio: 12000,
            },
            {
              id: 'BEB-34',
              img: '../icons/menu/be34.webp',
              nombre: 'Té Hatsu Blanco sabor Flor de Cerezo',
              desc: 'Suave mezcla de té blanco con el sabor natural de flor de cerezo.',
              precio: 12000,
            },
          ],
        },
        {
          cat: 'Cervezas 3 Cordilleras',
          items: [
            {
              id: 'CER-01',
              img: '../icons/menu/cc1.webp',
              nombre: 'Blanca | 3 Cordilleras',
              desc: 'Cerveza tipo Wheat Ale color dorado, la puerta a nuestro mundo de cervezas artesanales.',
              precio: 12000,
            },
            {
              id: 'CER-02',
              img: '../icons/menu/cc2.webp',
              nombre: 'Mulata | 3 Cordilleras',
              desc: 'Cerveza tipo Amber Ale de color rojo intenso, combina todas las variedades de maltas.',
              precio: 12000,
            },
            {
              id: 'CER-03',
              img: '../icons/menu/cc3.webp',
              nombre: 'Rosada | 3 Cordilleras',
              desc: 'Cerveza tipo Rosé que causó sorpresa en el mercado por su color y tonos.',
              precio: 12000,
            },
            {
              id: 'CER-04',
              img: '../icons/menu/cc4.webp',
              nombre: 'Mestiza | 3 Cordilleras',
              desc: 'Cerveza tipo American Pale Ale, una fiesta de lúpulos americanos.',
              precio: 12000,
            },
            {
              id: 'CER-05',
              img: '../icons/menu/cc5.webp',
              nombre: 'Negra | 3 Cordilleras',
              desc: 'Cerveza tipo Stout inspirada en los sabores de los Andes, cargada de maltas tostadas.',
              precio: 12000,
            },
            {
              id: 'CER-06',
              img: '../icons/menu/cc6.webp',
              nombre: 'Mona | 3 Cordilleras',
              desc: 'Cerveza Premium tipo Blonde Ale, en los límites de la artesanalidad.',
              precio: 12000,
            },
          ],
        },
        {
          cat: 'Mocktails',
          items: [
            {
              id: 'MOC-01',
              img: '../icons/menu/mo1.webp',
              nombre: 'Jamaiquino',
              desc: '(Foto sujeta a cambios y presentación) Concentrado sabor con zumo de limón.',
              precio: 14000,
            },
            {
              id: 'MOC-02',
              img: '../icons/menu/mo2.webp',
              nombre: 'Lulo Mojito',
              desc: '(Foto sujeta a cambios y presentación) La acidez del lulo con el sabor refrescante del Té Hatsu.',
              precio: 14000,
            },
            {
              id: 'MOC-03',
              img: '../icons/menu/mo3.webp',
              nombre: 'Mangostino Highball',
              desc: '(Foto sujeta a cambios y presentación) La canela se reconoce por sus propiedades calmantes y diuréticas.',
              precio: 14000,
            },
            {
              id: 'MOC-04',
              img: '../icons/menu/mo4.webp',
              nombre: 'Soda de Mango Biche',
              desc: '(Foto sujeta a cambios y presentación) Una Bretaña bien helada con limón y mango biche.',
              precio: 14000,
            },
            {
              id: 'MOC-05',
              img: '../icons/menu/mo5.webp',
              nombre: 'Caipineska',
              desc: '(Foto sujeta a cambios y presentación) El limón aporta propiedades como la vitamina C.',
              precio: 14000,
            },
            {
              id: 'MOC-06',
              img: '../icons/menu/mo6.webp',
              nombre: 'Pink Tonic',
              desc: '(Foto sujeta a cambios y presentación) Un mocktail con identidad propia.',
              precio: 14000,
            },
          ],
        },
        {
          cat: 'Cocteles',
          items: [
            {
              id: 'COC-01',
              img: '../icons/menu/co1.webp',
              nombre: 'Cuba Libre',
              desc: 'Ron, coca-cola y limón.',
              precio: 22000,
            },
            {
              id: 'COC-02',
              img: '../icons/menu/co2.webp',
              nombre: 'Alexander',
              desc: 'Brandy, licor de café y helado de vainilla.',
              precio: 27000,
            },
            {
              id: 'COC-03',
              img: '../icons/menu/co3.webp',
              nombre: 'Mojito Cubano',
              desc: 'Ron blanco, hierbabuena, limón y soda Bretaña.',
              precio: 22000,
            },
            {
              id: 'COC-04',
              img: '../icons/menu/co4.webp',
              nombre: 'Gin - Tonic',
              desc: 'Ginebra y tónica Canada Dry.',
              precio: 22000,
            },
            {
              id: 'COC-05',
              img: '../icons/menu/co5.webp',
              nombre: 'Cosmopolitan',
              desc: 'Vodka, triple sec y jugo de arándanos.',
              precio: 22000,
            },
            {
              id: 'COC-06',
              img: '../icons/menu/co6.webp',
              nombre: 'Piña Colada',
              desc: 'Ron, piña, triple sec y crema de coco.',
              precio: 27000,
            },
            {
              id: 'COC-07',
              img: '../icons/menu/co7.webp',
              nombre: 'Martini Peach',
              desc: 'Vodka, triple sec y licor de durazno.',
              precio: 22000,
            },
            {
              id: 'COC-08',
              img: '../icons/menu/co8.webp',
              nombre: 'Margarita',
              desc: 'Tequila, triple sec y zumo de limón.',
              precio: 22000,
            },
            {
              id: 'COC-09',
              img: '../icons/menu/co9.webp',
              nombre: 'Passion Fruit',
              desc: 'Vodka, triple sec y jugo de maracuyá.',
              precio: 22000,
            },
            {
              id: 'COC-10',
              img: '../icons/menu/co10.webp',
              nombre: 'Daiquiri Tropical',
              desc: 'Ron, maracuyá y mora.',
              precio: 22000,
            },
            {
              id: 'COC-11',
              img: '../icons/menu/co11.webp',
              nombre: 'La Pecera',
              desc: 'Vodka, ginebra, tequila, triple sec, fresas picadas, cerezas, jugo de naranja y jugo de arándanos.',
              precio: 50000,
            },
            {
              id: 'COC-12',
              img: '../icons/menu/co12.webp',
              nombre: 'Jarra de Tinto de Verano',
              desc: 'Coctel a base de vino tinto, licor de naranja y 7up. (Rinde para 5 copas)',
              precio: 90000,
            },
          ],
        },
        {
          cat: 'Licores',
          items: [
            {
              id: 'LIC-01',
              img: '../icons/menu/li1.webp',
              nombre: 'Tequila Don Julio Reposado',
              desc: 'Color paja con gran brillantez y tonos dorados, notas a agave cocido y miel.',
              precio: 780000,
            },
            {
              id: 'LIC-02',
              img: '../icons/menu/li2.webp',
              nombre: 'Whisky Macallan Double Cask 12 Years',
              desc: 'Forma parte de la colección Double Cask, estilo clásico Macallan con dulzura inigualable.',
              precio: 900000,
            },
            {
              id: 'LIC-03',
              img: '../icons/menu/li3.webp',
              nombre: "Whisky Buchanan's 18 Años",
              desc: 'Sabor intenso de primera línea, con profundidades de chocolate negro, cereza negra y almendras.',
              precio: 850000,
            },
            {
              id: 'LIC-04',
              img: '../icons/menu/li4.webp',
              nombre: "Whisky Buchanan's Master",
              desc: 'Suave y afrutado, con notas de naranja y chocolate, ideal con soda.',
              precio: 650000,
            },
            {
              id: 'LIC-05',
              img: '../icons/menu/li5.webp',
              nombre: "Whisky Jack Daniel's",
              desc: 'Dulce y picante, con foco de canela. En su final recuerda a galletas de canela.',
              precio: 300000,
            },
            {
              id: 'LIC-06',
              img: '../icons/menu/li6.webp',
              nombre: "Whisky Buchanan's Deluxe",
              desc: 'Mezcla brillante de notas cítricas de naranja, combinadas con chocolate y miel.',
              precio: 350000,
            },
            {
              id: 'LIC-07',
              img: '../icons/menu/li7.webp',
              nombre: 'Whisky Old Parr 12 Años',
              desc: 'Suave en la boca, dulce con mucha miel, pasas y canela, notas de frutas tropicales y naranjas.',
              precio: 370000,
            },
            {
              id: 'LIC-08',
              img: '../icons/menu/li8.webp',
              nombre: 'Crema de Whisky Baileys trago',
              desc: 'Baileys Original Irish Cream, la combinación más dulce de whisky y licor.',
              precio: 25000,
            },
            {
              id: 'LIC-09',
              img: '../icons/menu/li9.webp',
              nombre: 'Ron Viejo de Caldas 15 Años x 750 ml',
              desc: 'Gran reserva especial 15 años, de la caña de azúcar y añejado en barrica.',
              precio: 225500,
            },
            {
              id: 'LIC-10',
              img: '../icons/menu/li10.webp',
              nombre: 'Ron Viejo de Caldas 8 Años x 750 ml',
              desc: 'Sabor a madera, tostado con notas ácidas frutales, herbales y de coco.',
              precio: 180000,
            },
            {
              id: 'LIC-11',
              img: '../icons/menu/li11.webp',
              nombre: 'Ron Viejo de Caldas',
              desc: 'Tradicional, reconocido por su carácter y calidad excepcional.',
              precio: 120000,
            },
            {
              id: 'LIC-12',
              img: '../icons/menu/li12.webp',
              nombre: 'Aguardiente Amarillo de Manzanares',
              desc: 'Elaborado con la mejor caña gorobeta, anís sembrado en Guadalupe y agua pura de nacimiento.',
              precio: 120000,
            },
            {
              id: 'LIC-13',
              img: '../icons/menu/li13.webp',
              nombre: 'Aguardiente Antioqueño',
              desc: 'Elaborado con alcoholes extra puros, notas dulces y ligeramente suaves.',
              precio: 120000,
            },
            {
              id: 'LIC-14',
              img: '../icons/menu/li14.webp',
              nombre: 'Vodka Smirnoff de Lulo x 375 ml',
              desc: 'Combina un aroma fuerte con un dulce y ligero sabor a lulo.',
              precio: 120000,
            },
            {
              id: 'LIC-15',
              img: '../icons/menu/li15.webp',
              nombre: 'Vodka Absolut Regular x 375 ml',
              desc: 'Sabor rico con cuerpo y complejo, suave, con el carácter distintivo del grano de trigo.',
              precio: 100000,
            },
          ],
        },
        {
          cat: 'Vinos',
          items: [
            {
              id: 'VIN-01',
              img: '../icons/menu/vi1.webp',
              nombre: 'Marqués de Riscal Reserva',
              desc: 'Color cereza muy cubierto, intenso y con apenas signos de evolución. Nariz muy expresiva.',
              precio: 440000,
            },
            {
              id: 'VIN-02',
              img: '../icons/menu/vi2.webp',
              nombre: 'Trivento Golden Reserve Malbec',
              desc: 'Vino aromático con notas de ciruela, cereza y albaricoque silvestre.',
              precio: 350000,
            },
            {
              id: 'VIN-03',
              img: '../icons/menu/vi3.webp',
              nombre: 'Marqués de Casa Concha Merlot',
              desc: 'Delicadas notas de grosella, especias, frutos del bosque y ciruela roja.',
              precio: 310000,
            },
            {
              id: 'VIN-04',
              img: '../icons/menu/vi4.webp',
              nombre: 'Trivento Reserve Malbec',
              desc: 'Se destaca por su corazón frutal, volumen de boca y sensación golosa.',
              precio: 250000,
            },
            {
              id: 'VIN-05',
              img: '../icons/menu/vi5.webp',
              nombre: 'Casillero del Diablo Dark Red',
              desc: 'Deslumbra por su color rojo oscuro e intenso, con toques de frutas negras.',
              precio: 300000,
            },
            {
              id: 'VIN-06',
              img: '../icons/menu/vi6.webp',
              nombre: 'Casillero del Diablo Rosé',
              desc: 'Vino especial, elaborado con uvas tintas Shiraz vinificadas como blanco.',
              precio: 180000,
            },
            {
              id: 'VIN-07',
              img: '../icons/menu/vi7.webp',
              nombre: 'C.D Cabernet Sauvignon',
              desc: 'Intensos aromas a cerezas, ciruelas y toques a vainilla y tostado.',
              precio: 165000,
            },
            {
              id: 'VIN-08',
              img: '../icons/menu/vi8.webp',
              nombre: 'Casillero del Diablo Red Blend',
              desc: 'Maduro, con marcados aromas de cereza negra y ciruela, notas especiadas.',
              precio: 165000,
            },
            {
              id: 'VIN-09',
              img: '../icons/menu/vi9.webp',
              nombre: 'Casillero del Diablo Sauvignon Blanc',
              desc: 'Toque mineral, estilo refrescante y frío, con aromas a durazno y grosellas.',
              precio: 165000,
            },
            {
              id: 'VIN-10',
              img: '../icons/menu/vi10.webp',
              nombre: 'Casillero del Diablo Reserva Merlot',
              desc: 'Dócil, de suaves taninos, expresa frescor y dulzura.',
              precio: 165000,
            },
            {
              id: 'VIN-11',
              img: '../icons/menu/vi11.webp',
              nombre: 'Casillero del Diablo Malbec',
              desc: 'Dulces y redondos taninos, aromas a moras y ciruelas negras con pimienta y vainilla.',
              precio: 165000,
            },
            {
              id: 'VIN-12',
              img: '../icons/menu/vi12.webp',
              nombre: 'Casillero del Diablo Carmenere',
              desc: 'Variedad de Burdeos que florece en tierras chilenas, deliciosos aromas.',
              precio: 165000,
            },
            {
              id: 'VIN-13',
              img: '../icons/menu/vi13.webp',
              nombre: 'Frontera Carmenere',
              desc: 'Brillante color rojo rubí y tonos violáceos, aromas a ciruelas y especias.',
              precio: 165000,
            },
            {
              id: 'VIN-14',
              img: '../icons/menu/vi14.webp',
              nombre: 'Frontera Cabernet Sauvignon',
              desc: 'Ideal para disfrutar junto a los amigos y la familia.',
              precio: 110000,
            },
            {
              id: 'VIN-15',
              img: '../icons/menu/vi15.webp',
              nombre: 'Frontera Sauvignon Blanc',
              desc: 'Color amarillo verdoso y aroma frutal, con notas cítricas y a pera.',
              precio: 110000,
            },
            {
              id: 'VIN-16',
              img: '../icons/menu/vi16.webp',
              nombre: 'Cono Sur Reserva Especial Pinot Noir',
              desc: 'Del Valle de San Antonio, vino rojo-morado claro, profundo y brillante.',
              precio: 130000,
            },
            {
              id: 'VIN-17',
              img: '../icons/menu/vi17.webp',
              nombre: 'Cono Sur Bicicleta Sauvignon B.',
              desc: 'Finas notas a pomelo combinadas con aromas a manzanas verdes y duraznos blancos.',
              precio: 110000,
            },
            {
              id: 'VIN-18',
              img: '../icons/menu/vi18.webp',
              nombre: 'Cono Sur Bicicleta Merlot',
              desc: 'Aromas a frutos rojos, frutos del bosque y notas a cacao, mocha y tabaco.',
              precio: 110000,
            },
            {
              id: 'VIN-19',
              img: '../icons/menu/vi19.webp',
              nombre: 'Cono Sur Bicicleta Cabernet S.',
              desc: 'Notas de ciruela, frambuesa y especias dulces, con chocolate y vainilla.',
              precio: 110000,
            },
            {
              id: 'VIN-20',
              img: '../icons/menu/vi20.webp',
              nombre: 'Cono Sur Bicicleta Carmenere',
              desc: 'Notas frutales de guinda negra con toques de café, pimienta y tostado.',
              precio: 110000,
            },
            {
              id: 'VIN-21',
              img: '../icons/menu/vi21.webp',
              nombre: 'Lambrusco Rosato',
              desc: 'Sabor suave y envolvente, fresco y ligero, notas frutales.',
              precio: 90000,
            },
          ],
        },
        {
          cat: 'Champagnes',
          items: [
            {
              id: 'CHA-01',
              img: '../icons/menu/ch1.webp',
              nombre: 'Veuve Clicquot Rose Box',
              desc: 'El primer champán rosado mezclado conocido en el mundo, viveza y explosión de frutas.',
              precio: 1200000,
            },
            {
              id: 'CHA-02',
              img: '../icons/menu/ch2.webp',
              nombre: 'M&C Brut Imperial',
              desc: 'Mucha intensidad a manzana verde y cítricos, aromas minerales y a flores blancas.',
              precio: 700000,
            },
            {
              id: 'CHA-03',
              img: '../icons/menu/ch3.webp',
              nombre: 'Chandon Rosé',
              desc: 'El perfecto equilibrio entre frescura y cremosidad, agradable sensación dulce.',
              precio: 180000,
            },
            {
              id: 'CHA-04',
              img: '../icons/menu/ch4.webp',
              nombre: 'Codorníu Clásico',
              desc: 'Codorníu Clásico Brut, el tradicional por antonomasia.',
              precio: 180000,
            },
          ],
        },
      ];
      const SUGERENCIAS = {
        Entradas: ['Salsa aparte', 'Sin picante', 'Para compartir'],
        'Para Compartir': ['Extra salsa', 'Sin picante', 'Para compartir'],
        'De la Parrilla': ['Término medio', 'Bien asado', 'Salsa aparte'],
        'Angus Beef': ['Término medio', 'Bien asado', 'Salsa aparte'],
        'Burger Angus': ['Sin cebolla', 'Extra queso', 'Papas aparte'],
        'De la Casa': ['Sin picante', 'Salsa aparte', 'Poca sal'],
        'Del Mar': ['Sin picante', 'Salsa aparte', 'Limón aparte'],
        'Menú Infantil': ['Sin salsa', 'Papas extra', 'Sin picante'],
        Postres: ['Sin crema', 'Salsa aparte', 'Para compartir'],
        Bebidas: ['Sin hielo', 'Sin azúcar', 'Leche aparte'],
        'Cervezas 3 Cordilleras': ['Bien fría', 'Sin vaso', 'Vaso aparte'],
        Mocktails: ['Sin hielo', 'Menos dulce', 'Sin azúcar'],
        Cocteles: ['Sin hielo', 'Menos dulce', 'Sin alcohol'],
        Licores: ['Con hielo', 'Solo', 'Con soda'],
        Vinos: ['Bien frío', 'Temperatura ambiente', 'Copas aparte'],
        Champagnes: ['Bien frío', 'Copas aparte', 'Para compartir'],
      };

      const SUGERENCIAS_POR_PRODUCTO = {
        'ENT-01': ['Con pollo', 'Con champiñones', 'Sin picante'],
        'ENT-03': ['Salsa golf', 'Salsa roja', 'Sin picante'],
        'ENT-04': ['Sin tomate', 'Sin aguacate', 'Salsa aparte'],
        'COM-07': ['Salsa BBQ', 'Salsa miel-mostaza', 'Menos picante'],
        'PAR-08': ['Salsa BBQ', 'Salsa ahumada', 'Salsa aparte'],
        'CAS-01': ['Salsa aparte', 'Sin picante', 'Poca sal'],
        'MAR-01': ['Limón aparte', 'Salsa aparte', 'Sin picante'],
      };

      function sugerenciasParaItem(item) {
        if (!item) return [];
        if (SUGERENCIAS_POR_PRODUCTO[item.id]) return SUGERENCIAS_POR_PRODUCTO[item.id];
        const texto = `${item.nombre} ${item.desc}`.toLowerCase();
        if (/cafe|café|chocolate|te |té |infusion|infusión/.test(texto)) {
          return ['Sin azúcar', 'Leche aparte', 'Bien caliente'];
        }
        if (/res|churrasco|lomo|bife|punta de anca|baby beef|carne/.test(texto)) {
          return ['Término medio', 'Bien asado', 'Salsa aparte'];
        }
        if (/pollo|cerdo|chicharron|chicharrón|morcilla|chorizo/.test(texto)) {
          return ['Bien asado', 'Salsa aparte', 'Poca sal'];
        }
        return (SUGERENCIAS[item.cat] || []).slice(0, 3);
      }
